export const protectedRoutes = new Set(['/api/site', '/api/latest', '/api/post']);

export const routes = {
	'/feed': 'feed.xml',
	'/sitemap.xml': 'sitemap.xml',
	'/sitemap-page.xml': 'sitemap-page.xml',
	'/sitemap-category.xml': 'sitemap-category.xml',
	'/ads.txt': 'ads.txt',
	'/robots.txt': 'robots.txt',
	'/api/site': 'site.json',
	'/api/latest': 'latest.json',
};

export const endpoints = {
	p1: 'https://storage1.viethoaduc-12.workers.dev',
	p2: 'https://storage2.thetimenews-us.workers.dev',
	p3: 'https://storage3.viethoaduc-21.workers.dev',
	p4: 'https://storage4.viethoaduc-21.workers.dev',
	p5: 'https://storage5.jenkinsapp-notification.workers.dev',
	p6: 'https://storage6.jenkinsapp-notification.workers.dev',
	p7: 'https://storage7.viethoaduc-12.workers.dev',
	p8: 'https://storage8.carlosantonio-thetimes.workers.dev',
	p9: 'https://storage9.carlosantonio-thetimes.workers.dev',
	p10: 'https://storage10.thetimenews-us.workers.dev',
	p11: 'https://storage11.chloemadison-pad.workers.dev',
	p12: 'https://storage12.chloemadison-pad.workers.dev',
	p13: 'https://storage13.anhduong-pad27.workers.dev',
	p14: 'https://storage14.anhduong-pad27.workers.dev',
	p15: 'https://storage15.chienmai1011.workers.dev',
	p16: 'https://storage16.chienmai1011.workers.dev',
	p17: 'https://storage17.viethoaduc-14.workers.dev',
	p18: 'https://storage18.viethoaduc-14.workers.dev',
	p19: 'https://storage19.alabama-center-network.workers.dev',
	p20: 'https://storage20.alabama-center-network.workers.dev',
	p21: 'https://storage21.duong-anhpham21.workers.dev',
	p22: 'https://storage22.duong-anhpham21.workers.dev',
	p23: 'https://storage23.viethoaduc-32.workers.dev',
	p24: 'https://storage24.viethoaduc-32.workers.dev',
	p25: 'https://storage25.viethoaduc-31.workers.dev',
	p26: 'https://storage26.viethoaduc-31.workers.dev',
	p27: 'https://storage27.youngladdy2.workers.dev',
	p28: 'https://storage28.youngladdy2.workers.dev',
	p29: 'https://storage29.hoaducviet2002.workers.dev',
	p30: 'https://storage30.hoaducviet2002.workers.dev',
	p31: 'https://storage31.viethoaduc-13.workers.dev',
	p32: 'https://storage32.viethoaduc-13.workers.dev',
	p33: 'https://storage33.chloemadison-alex1.workers.dev',
	p34: 'https://storage34.chloemadison-alex1.workers.dev',
	p35: 'https://storage35.chloemadison-alex771.workers.dev',
	p36: 'https://storage36.chloemadison-alex771.workers.dev',
	p37: 'https://storage37.leminhvu-sor21.workers.dev',
	p38: 'https://storage38.leminhvu-sor21.workers.dev',
	p39: 'https://storage39.jenkins-application.workers.dev',
	p40: 'https://storage40.jenkins-application.workers.dev',
	p41: 'https://storage41.hoaducviet1111.workers.dev',
	p42: 'https://storage42.hoaducviet1111.workers.dev',
	p43: 'https://storage43.davidpower.workers.dev',
	p44: 'https://storage44.davidpower.workers.dev',
	p45: 'https://storage45.viethoa-11.workers.dev',
	p46: 'https://storage46.viethoa-11.workers.dev',
};
